# Generated by Django 2.0.9 on 2018-11-06 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('visa', 'Visa'), ('rent', 'Rent'), ('qanda', 'Q&A')], default='georgia', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(related_name='posts_liked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='region',
            field=models.CharField(choices=[('georgia', 'Georgia'), ('new_york', 'New York'), ('los_angeles', 'Los Angeles'), ('san_francisco', 'San Francisco')], default='georgia', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
