# Generated by Django 2.0.9 on 2018-12-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20181122_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('visa', 'Visa'), ('rent', 'Rent'), ('qanda', 'Q&A'), ('sell', 'Sell'), ('buy', 'Buy')], default='georgia', max_length=100),
        ),
    ]
