# Generated by Django 2.0.9 on 2018-12-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20181213_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='region',
            field=models.CharField(choices=[('georgia', 'Georgia'), ('new-york', 'New York'), ('los-angeles', 'Los Angeles'), ('seattle', 'Seattle')], default='georgia', max_length=100),
        ),
    ]
