# Generated by Django 2.0.9 on 2018-11-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181103_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
        migrations.AddField(
            model_name='user',
            name='nike_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nick Name'),
        ),
    ]
