# Generated by Django 2.0.9 on 2018-11-06 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181106_0439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nike_name',
            new_name='nick_name',
        ),
    ]
